### PR TITLE
Sass version update, Dependencies update, and Tests regex fix.

### LINKED ISSUE #67: Why is the sass version locked to 1.7.2?
Why is the sass version locked to 1.7.2?
I think it would be beneficial to use never versions. Correct me if I am missing something.

I need the importing of CSS same as @LucaMele in #50 
According to the docu of SASS-LANG the sass lib supports this since 1.11.0:
https://sass-lang.com/documentation/at-rules/import#importing-css

### PR DESCRIPTION
**Pull request by elycruz**
Fixes: #67 , #66
### Changes:
package.json:
  - Updated all depedencies to be 'greater than or equal' to their current versions.
src/index.js - Removed 'fs-extra' as a dependency of the file (node v0.10+
    provides 'fs.promises' (these make code a little more straight forward)).
- Added 'engines'  key to package.json (helps to set realistic expectations for supported node versions).
- test/index - Updated regex in 'squash' function to do global search instead of just first character (this was the reason tests were failing on windows) .
- Added '.idea' dir to '.gitignore'.
- Added .editorconfig (helps to enforce white space formatting in project files).

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -2,14 +2,14 @@ import pify from 'pify'
 import resolve from 'resolve';
 import sass from 'sass';
 import { dirname } from 'path';
-import { writeFileSync } from 'fs';
-import { isString, isFunction } from 'util';
```
Comment (elycruz) [inline src/index.js:6]: Node has these marked as deprecated (they recommend to just use `typeof`).
